// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: privval/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceFeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RawData []byte `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
}

func (x *PriceFeedRequest) Reset() {
	*x = PriceFeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceFeedRequest) ProtoMessage() {}

func (x *PriceFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceFeedRequest.ProtoReflect.Descriptor instead.
func (*PriceFeedRequest) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *PriceFeedRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PriceFeedRequest) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type PriceFeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *PriceFeedResponse) Reset() {
	*x = PriceFeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceFeedResponse) ProtoMessage() {}

func (x *PriceFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceFeedResponse.ProtoReflect.Descriptor instead.
func (*PriceFeedResponse) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *PriceFeedResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PriceFeedResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{2}
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{3}
}

type OracleStreamMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Sum:
	//
	//	*OracleStreamMessage_PriceFeedRequest
	//	*OracleStreamMessage_PriceFeedResponse
	//	*OracleStreamMessage_Ping
	//	*OracleStreamMessage_Pong
	Sum isOracleStreamMessage_Sum `protobuf_oneof:"sum"`
}

func (x *OracleStreamMessage) Reset() {
	*x = OracleStreamMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_privval_v1_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OracleStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleStreamMessage) ProtoMessage() {}

func (x *OracleStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_privval_v1_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleStreamMessage.ProtoReflect.Descriptor instead.
func (*OracleStreamMessage) Descriptor() ([]byte, []int) {
	return file_privval_v1_types_proto_rawDescGZIP(), []int{4}
}

func (m *OracleStreamMessage) GetSum() isOracleStreamMessage_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (x *OracleStreamMessage) GetPriceFeedRequest() *PriceFeedRequest {
	if x, ok := x.GetSum().(*OracleStreamMessage_PriceFeedRequest); ok {
		return x.PriceFeedRequest
	}
	return nil
}

func (x *OracleStreamMessage) GetPriceFeedResponse() *PriceFeedResponse {
	if x, ok := x.GetSum().(*OracleStreamMessage_PriceFeedResponse); ok {
		return x.PriceFeedResponse
	}
	return nil
}

func (x *OracleStreamMessage) GetPing() *Ping {
	if x, ok := x.GetSum().(*OracleStreamMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *OracleStreamMessage) GetPong() *Pong {
	if x, ok := x.GetSum().(*OracleStreamMessage_Pong); ok {
		return x.Pong
	}
	return nil
}

type isOracleStreamMessage_Sum interface {
	isOracleStreamMessage_Sum()
}

type OracleStreamMessage_PriceFeedRequest struct {
	PriceFeedRequest *PriceFeedRequest `protobuf:"bytes,1,opt,name=price_feed_request,json=priceFeedRequest,proto3,oneof"`
}

type OracleStreamMessage_PriceFeedResponse struct {
	PriceFeedResponse *PriceFeedResponse `protobuf:"bytes,2,opt,name=price_feed_response,json=priceFeedResponse,proto3,oneof"`
}

type OracleStreamMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type OracleStreamMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

func (*OracleStreamMessage_PriceFeedRequest) isOracleStreamMessage_Sum() {}

func (*OracleStreamMessage_PriceFeedResponse) isOracleStreamMessage_Sum() {}

func (*OracleStreamMessage_Ping) isOracleStreamMessage_Sum() {}

func (*OracleStreamMessage_Pong) isOracleStreamMessage_Sum() {}

var File_privval_v1_types_proto protoreflect.FileDescriptor

var file_privval_v1_types_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a, 0x10, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x11, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x06, 0x0a,
	0x04, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x8b, 0x02, 0x0a, 0x13, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4c, 0x0a,
	0x12, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x10, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x13, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x76,
	0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6f, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x42, 0x05, 0x0a, 0x03,
	0x73, 0x75, 0x6d, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6d, 0x75, 0x61, 0x2d, 0x78, 0x79, 0x7a, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x2d, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x6c, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_privval_v1_types_proto_rawDescOnce sync.Once
	file_privval_v1_types_proto_rawDescData = file_privval_v1_types_proto_rawDesc
)

func file_privval_v1_types_proto_rawDescGZIP() []byte {
	file_privval_v1_types_proto_rawDescOnce.Do(func() {
		file_privval_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_privval_v1_types_proto_rawDescData)
	})
	return file_privval_v1_types_proto_rawDescData
}

var file_privval_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_privval_v1_types_proto_goTypes = []any{
	(*PriceFeedRequest)(nil),    // 0: privval.v1.PriceFeedRequest
	(*PriceFeedResponse)(nil),   // 1: privval.v1.PriceFeedResponse
	(*Ping)(nil),                // 2: privval.v1.Ping
	(*Pong)(nil),                // 3: privval.v1.Pong
	(*OracleStreamMessage)(nil), // 4: privval.v1.OracleStreamMessage
}
var file_privval_v1_types_proto_depIdxs = []int32{
	0, // 0: privval.v1.OracleStreamMessage.price_feed_request:type_name -> privval.v1.PriceFeedRequest
	1, // 1: privval.v1.OracleStreamMessage.price_feed_response:type_name -> privval.v1.PriceFeedResponse
	2, // 2: privval.v1.OracleStreamMessage.ping:type_name -> privval.v1.Ping
	3, // 3: privval.v1.OracleStreamMessage.pong:type_name -> privval.v1.Pong
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_privval_v1_types_proto_init() }
func file_privval_v1_types_proto_init() {
	if File_privval_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_privval_v1_types_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PriceFeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PriceFeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_privval_v1_types_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OracleStreamMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_privval_v1_types_proto_msgTypes[4].OneofWrappers = []any{
		(*OracleStreamMessage_PriceFeedRequest)(nil),
		(*OracleStreamMessage_PriceFeedResponse)(nil),
		(*OracleStreamMessage_Ping)(nil),
		(*OracleStreamMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_privval_v1_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_privval_v1_types_proto_goTypes,
		DependencyIndexes: file_privval_v1_types_proto_depIdxs,
		MessageInfos:      file_privval_v1_types_proto_msgTypes,
	}.Build()
	File_privval_v1_types_proto = out.File
	file_privval_v1_types_proto_rawDesc = nil
	file_privval_v1_types_proto_goTypes = nil
	file_privval_v1_types_proto_depIdxs = nil
}
